### ISSUE TITLE
[Guilds] [Bug] A list of current state bugs that we found

### ISSUE THREAD

**Issue by Wextra** [Senre-MC/senre-mc.github.io#2]
/s claim does not seem to be working. While claiming chunks adjacent to the state and part of the nation, player gets the message that the claims overlap. Nothing is shown in console except for locale errors. When trying to claim Unclaimed chunk as a state, "null, State.java, claimChunk_80".

When player executes /s spawn, player gets sent to coordinates 15 81 16349 except for somewhere around 16361 41 4744 which it should be. This includes both right after creating the state and after doing /s set spawn. Nothing is shown in console except for locale errors.

As a nation owner not part of state, doing /s info <name> does not work. Shows Command Not Recognized prompt. For the player who runs the state, /s info does work though.

/s form does not work. Returns "Null, Proconditions.java, outOfBounds:64"

Disbanding a state removes the state owner from the state, but the state still exists in the nation. After disbanding a state, the ex-state owner can no longer be granted a new state. Error message "null, NationCommand.java, addstate_STRING_NPOP:348"

**Comment by Wextra** [comment]
Found this in the logs regarding the last sentence regarding that the ex-state owner can no longer be granted a new state.

[15:48:35 INFO]: Wextra issued server command: /n addstate Bob tuplaa
[15:48:35 WARN]: java.lang.reflect.InvocationTargetException
[15:48:35 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:48:35 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:48:35 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:48:35 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:48:35 WARN]:        at org.guilds.plugin.commands.CommandEngine.call(CommandEngine.java:312)
[15:48:35 WARN]:        at org.guilds.plugin.commands.CommandEngine.onCommand(CommandEngine.java:367)
[15:48:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:48:35 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:48:35 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[15:48:35 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[15:48:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:48:35 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.guilds.plugin.provider.IResident.getPlayer()" because "lord" is null
[15:48:35 WARN]:        at org.guilds.plugin.command.mechanic.NationCommand.addstate_STRING_NPOP(NationCommand.java:348)
[15:48:35 WARN]:        ... 26 more

**Comment by Senre-MC** [comment]
All reported bugs have been transferred to Guilds and reformatted accordingly.
