### ISSUE TITLE
Nation behaving weirdly after restart

### ISSUE THREAD

**Issue by Wextra** [Senre-MC/senre-mc.github.io#4]
After restart, the nation changed name to "null" and its stats were reset. Players are still part of the nation and the nation still has its claims, but mandate has been reset to 50.00. The state that existed in the nation has disappeared.

Guilds also continuously displays this error in console:
[16:02:13 WARN]: [Guilds] Task #36 for Guilds v1.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.guilds.plugin.provider.IHoldingEntity.getUUID()" because the return value of "org.guilds.plugin.provider.IRank.getHolding()" is null
        at org.guilds.plugin.player.ResidentFormatBeta10.putRank(ResidentFormatBeta10.java:197) ~[?:?]
        at org.guilds.plugin.player.ResidentFormatBeta10.compile(ResidentFormatBeta10.java:35) ~[?:?]
        at org.guilds.plugin.player.Resident.autosave(Resident.java:75) ~[?:?]
        at org.guilds.plugin.Main$2.run(Main.java:214) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-775]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-775]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Senre-MC** [comment]
This type of error specifically happens when saving fails to occur. I will need to know how to recreate this

**Comment by Senre-MC** [comment]
Bug found and patched
